-- Read-only business-rule checks. Run after importing source CSVs.
-- Complete column, key and foreign-key profiles are generated by scripts/analyze.py.

-- 1. Missing item coverage is different from an orphaned child key.
SELECT COUNT(*) AS orders_without_items
FROM orders o LEFT JOIN (SELECT DISTINCT order_id FROM order_items) i ON o.order_id=i.order_id
WHERE i.order_id IS NULL;

-- 2. Customer chronology.
SELECT COUNT(*) AS orders_before_signup
FROM orders o JOIN customers c ON o.customer_id=c.customer_id
WHERE o.order_date<c.signup_date;

-- 3. Repeated return references. Extra records are not automatically duplicates.
SELECT COUNT(*)-COUNT(DISTINCT order_item_id) AS extra_return_records FROM returns;

-- 4. Compare cumulative item refunds with the recorded item value.
SELECT COUNT(*) AS excessive_refund_items, SUM(r.refund_amount-i.qty*i.price) AS refund_excess
FROM order_items i
JOIN (SELECT order_item_id,SUM(refund) AS refund_amount FROM returns GROUP BY order_item_id) r
ON i.order_item_id=r.order_item_id
WHERE r.refund_amount>i.qty*i.price;

-- 5. Aggregate independently to avoid fanout in payment reconciliation.
SELECT COUNT(*) AS order_headers,
       SUM(CASE WHEN ABS(COALESCE(i.item_sales,0)-p.payment_amount)>.01 THEN 1 ELSE 0 END) AS mismatches,
       SUM(COALESCE(i.item_sales,0))-SUM(p.payment_amount) AS aggregate_gap
FROM orders o
LEFT JOIN (SELECT order_id,SUM(qty*price) AS item_sales FROM order_items GROUP BY order_id) i ON o.order_id=i.order_id
LEFT JOIN (SELECT order_id,SUM(amount) AS payment_amount FROM payments GROUP BY order_id) p ON o.order_id=p.order_id;

-- 6. Diagnostic scenario only: hypothesize that discount is a percentage.
SELECT SUM(CASE WHEN ABS(COALESCE(i.item_sales,0)*(1-promo.discount/100.0)-p.payment_amount)<=.01 THEN 1 ELSE 0 END) AS scenario_matching_orders
FROM orders o JOIN promotions promo ON o.promotion_id=promo.promotion_id
LEFT JOIN (SELECT order_id,SUM(qty*price) AS item_sales FROM order_items GROUP BY order_id) i ON o.order_id=i.order_id
LEFT JOIN (SELECT order_id,SUM(amount) AS payment_amount FROM payments GROUP BY order_id) p ON o.order_id=p.order_id;

-- 7. Transaction/catalog pricing.
SELECT COUNT(*) AS compared_items, SUM(CASE WHEN i.price<>p.price THEN 1 ELSE 0 END) AS different_prices
FROM order_items i JOIN products p ON i.product_id=p.product_id;

-- 8. Actual cardinality of each order-linked operational fact.
SELECT 'payments' AS source_table,COUNT(*) AS row_count,COUNT(DISTINCT order_id) AS distinct_orders FROM payments
UNION ALL
SELECT 'shipments',COUNT(*),COUNT(DISTINCT order_id) FROM shipments;

-- 9. Verify remaining dimension and operational relationships.
SELECT 'orders_store' AS relationship,COUNT(*) AS unmatched FROM orders c LEFT JOIN stores p ON c.store_id=p.store_id WHERE p.store_id IS NULL
UNION ALL SELECT 'orders_promotion',COUNT(*) FROM orders c LEFT JOIN promotions p ON c.promotion_id=p.promotion_id WHERE p.promotion_id IS NULL
UNION ALL SELECT 'products_category',COUNT(*) FROM products c LEFT JOIN categories p ON c.category_id=p.category_id WHERE p.category_id IS NULL
UNION ALL SELECT 'products_supplier',COUNT(*) FROM products c LEFT JOIN suppliers p ON c.supplier_id=p.supplier_id WHERE p.supplier_id IS NULL
UNION ALL SELECT 'employees_store',COUNT(*) FROM employees c LEFT JOIN stores p ON c.store_id=p.store_id WHERE p.store_id IS NULL
UNION ALL SELECT 'payments_order',COUNT(*) FROM payments c LEFT JOIN orders p ON c.order_id=p.order_id WHERE p.order_id IS NULL
UNION ALL SELECT 'shipments_order',COUNT(*) FROM shipments c LEFT JOIN orders p ON c.order_id=p.order_id WHERE p.order_id IS NULL
UNION ALL SELECT 'returns_item',COUNT(*) FROM returns c LEFT JOIN order_items p ON c.order_item_id=p.order_item_id WHERE p.order_item_id IS NULL;
